### ISSUE TITLE
Unable to use custom serialize name

### ISSUE THREAD

**Issue by ragingdave** [spatie/laravel-model-states#132]
In attempting to use this, there seems to be a bug around how the static property name is handled.

If the static name is set, the state is unable to transition and you get the error of:
```
State field `state` expects state to be of type `App\TaskState`, instead got `resolved`
```

It seems that it's either prematurely serializing the State, or something, but basically that functionality is completely broken atm.

Code to demonstrate:
```
        $this->addState('state', TaskState::class)
            ->default(Open::class)
            ->allowTransition(Open::class, Resolved::class);
```
```
class Open extends TaskState
{
    public static $name = 'open';
}
```
```
class Resolved extends TaskState
{
    public static $name = 'resolved';
}
```

The package will not even set the default with the name set so that feature just doesn't work at all (https://spatie.be/docs/laravel-model-states/v1/working-with-states/02-serializing-states).

**Comment by brendt** [comment]
Can you reproduce the same result with the v2 branch? I'm close to tagging that one, and it solves all serialization issues thanks to Laravel's casting. Only thing holding me back is that it requires Laravel 8, and we can't test it yet in our own projects because other dependencies don't support it yet. I'm not going to fix v1 serialization issues anymore, because honestly they are a mess. If you really need v1, you can submit a tested PR and I'll be happy to merge it.
