### ISSUE TITLE
Nullable starting state

### ISSUE THREAD

**Issue by asantibanez** [spatie/laravel-model-states#147]
Hello @brendt ! Really loving the package. Thanks for sharing.

I am curious to know if the state field can be nullable from the start. 

Eg

```php
// SalesOrder model migration
$table->string('status'); // registered, approved, processed
$table->string('fulfillment')->nullable(); //null, pending, fulfilled
```

I am looking to implement these transitions:
status:          registered -> approved -> processed
fulfillment:   null             -> pending   -> fulfilled

Is there a way to define a starting state as nullable? Thanks in advance.

**Comment by brendt** [comment]
Hi @asantibanez 

If you're not adding `default` state in your state config, the default will be `null`. That also means you can't call a transition on `null` though:

```
$model->state->transitionTo(Pending::class);
```

If `state` is `null`, you'll get an error. Right now there's no way to allow a transition from `null` to a state. I'm not sure whether it's worth investing time in that, since it would mean we'd need to do lots more null checks, not only in the package but also in project code.

I think the better solution is to make some kind of "null state" and have that as the default. I'd suggest looking at the null object pattern if you want more details.

Hope that helps!
