### ISSUE TITLE
ErrorException Undefined index: App\Components\Workflow\States\Pending

### ISSUE THREAD

**Issue by peterkacinec** [spatie/laravel-model-states#151]
Hi, I have got this error, when I try to use package.

`ErrorException
Undefined index: App\Components\Workflow\States\Pending `

Error is in StateCaster class, get function and this line: `$stateClassName = $mapping[$value];` One line before is `$mapping = $this->getStateMapping();` and $mapping returns empty Collection. It's ok?

My code:
```php
<?php

namespace App\Components\Workflow;

use App\Components\Workflow\States\Paid;
use App\Components\Workflow\States\Pending;
use Spatie\ModelStates\State;
use Spatie\ModelStates\StateConfig;

abstract class ClaimState extends State
{
    abstract public function color(): string;

    public static function config(): StateConfig
    {
        return parent::config()
            ->default(Pending::class)
            ->allowTransition(Pending::class, Paid::class)
            ;
    }
}
```

```php
<?php

namespace App\Components\Workflow\States;

use App\Components\Workflow\ClaimState;

class Pending extends ClaimState
{
    public function color(): string
    {
        return 'green';
    }
}
```

```php
<?php

namespace App\Components\Workflow\States;

use App\Components\Workflow\ClaimState;

class Paid extends ClaimState
{
    public function color(): string
    {
        return 'green';
    }
}
```

```php
class Claim extends Model
{
    use HasStates;

    protected $casts = [
        'state' => ClaimState::class,
    ];
}
```

**Comment by brendt** [comment]
Please read https://spatie.be/docs/laravel-model-states/v2/working-with-states/02-serializing-states

States and their abstract class _must_ be in the same directory.

**Comment by isaac-souza** [comment]
> Please read https://spatie.be/docs/laravel-model-states/v2/working-with-states/02-serializing-states
> 
> States and their abstract class _must_ be in the same directory.

From the docs:

"There's one caveat if you're using custom names: you'll need to make sure they can be resolved back from the database. In order to do so, the package requires you to keep the abstract state class and its concrete implementations together in the same directory, which allows them to be resolved automatically."

The docs says that they only need to be in the same directory if custom names are being used.

So, are the docs incorrect? The abstract class and the concrete classes need to be in the same directory always not matter what.

I was getting the same error as mentioned in this issue, and as soon as I moved the abstract class to the same folder as the concrete one it worked.
