### ISSUE TITLE
Transition doesn't work when using model mutators

### ISSUE THREAD

**Issue by pszucs** [spatie/laravel-model-states#158]
I've created [a repository](https://github.com/pszucs/spatie-laravel-model-states-transitions-using-mutators) in order for you to be able to quickly recreate the issue.

Steps to reproduce:
- pull the repository
- set up the db connection
- run the migrations
- and execute the code found in the README.txt file (also pasted in here)

```php
$transaction = new Transaction();
$transaction->reference = 1;
$transaction->save();

// state is 'draft', as expected

$transaction->state->transitionTo(ProcessingState::class);
$transaction->save();

// state is still 'draft', but it should be 'processing'
```

The use case for the `setStateAttribute` mutator is that I need to set an additional property to `null` in some instances. This additional property is set when using a custom transition class, but in every other cases it is an information that is not needed, irrelevant to the state.

For example: when a payment fails, a custom transition class fills the additional attribute with information about why the payment failed. However, when a state then changes to something like "Processed" or "Closed" then this information is no longer relevant and I want to set it back to `null` (without having to write custom transition classes for every state change).

But when the mutator is executed on the model the state does not change. The transition without using mutators works.

Note: the `setStateAttribute` trick works with the previous (1.x) version of the package on Laravel 8 - hence the idea that it may be something wrong with the new version of this awesome package.

**Comment by brendt** [comment]
Hi @pszucs, thanks for reporting! 

The fact that it did work in v1 wasn't really a feature but rather a side effect of not being able to use custom casts. v2 does use custom casts provided by Laravel 8, and it's my suspicion that that's where the problem lies. In other words: I suspect it's an issue with Laravel casting. 

My best advice would be to debug this further and figure out why exactly mutators don't work when combined with casts. Please feel free to report back if it turns out to be a package issue after all!

**Comment by pszucs** [comment]
OK, thanks.
