### ISSUE TITLE
PHP 7.1 compatibility

### ISSUE THREAD

**Issue by maciejfikus** [spatie/laravel-model-states#45]
Hey
I found that package and hoped to use that in my ongoing project, however my project is business-limited to php 7.1 and Laravel 5.7 currently.
As I briefly looked through the code I am unable to say why it require minimum of 7.2 and Laravel 5.8 (while 5.8 requirment is php 7.1), can you point me to the right direction, which part of the code is behind this decission? 
And in case it is something quite trival, would you consider accepting a PR for 7.1 compatibility? I know 7.1 is basically EOL in one month but what can I say, I am not the one to make rules :-)

Thanks in advance

**Comment by brendt** [comment]
Our company policy is that we only actively support the latest one or two active PHP versions. It's our way of helping the community to keep up-to-date — and safe — with the current PHP ecosystem. Updating from 7.1 to 7.3 should maybe take a few hours given the right tools, eg: php-cs-fixer and rector. I'd highly recommend your managers to consider investing this small amount of time, because it'll be worth it big time. You can tell them you'd have to implement this package by hand otherwise, which costs the same amount of time 🙂
