### ISSUE TITLE
States homonymy

### ISSUE THREAD

**Issue by grcasanova** [spatie/laravel-model-states#58]
How to deal with multiple models having states with the same name?

**Comment by brendt** [comment]
That's not possible. Besides the technical implications, how would developers make distinction between the two states?

**Comment by sebastiandedeyne** [comment]
I assume you mean across different models, like a `User` and a `Product` both having an `Active` state.

In our projects, that problem is solved by having them in different namespaces. Check out @brendt's blog post on domains to learn more about how we structure our apps.

https://stitcher.io/blog/laravel-beyond-crud-01-domain-oriented-laravel

**Comment by brendt** [comment]
I misread the question indeed, thanks for clarifying Seb!
