### ISSUE TITLE
Question: Can transitions be adhered to on update?

### ISSUE THREAD

**Issue by booni3** [spatie/laravel-model-states#61]
From the docs is appears that you can only check transition logic with `$doc->transitionTo($status);`?

Am I correct in thinking that this kind of thing will currently bypass any transition checks?

```php
self::update([
    'state' => Pending::class
]);
```

**Comment by brendt** [comment]
That's correct, if you don't explicitly use transitions, no checks are done.

**Comment by booni3** [comment]
Is this by design? Do you think there is a potential for this to a) be implemented and b)wanted/needed? I would be happy to look at a PR if so.

In my case am wanting to safeguard records from being update to an invalid status, no matter how it is actioned.

**Comment by brendt** [comment]
It's by design: the package _can_ be used without transitions. Furthermore, I've had cases in my own projects where you don't want to use transitions, and simply "brute-force" set the state. Think about a super admin being able to change the state, no matter what, without side effects.

If you have any ideas on how to add "bulk" functionality, without using `::create` or `::update`, you're welcome to further discuss them here!
