### ISSUE TITLE
Using loadCount() on model resets the state to it's default state

### ISSUE THREAD

**Issue by TijlCl** [spatie/laravel-model-states#94]
Calling `$model->loadCount($relation)` resets the state to its default state.

**Comment by brendt** [comment]
This has to do with the event hooks which serialise the state fields, I'm working on a new version making use of Laravel's custom casting functionality, but it's taking longer because there were some unforeseen issues.

You're free to submit a PR which fixes this, or submit a PR with a failing test so that I can try to fix it.
